; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = lolin32

[common]
debug_level = 0

[env]
platform = espressif32 @ 6.9.0
framework = arduino
build_type = release
lib_ldf_mode = chain
;upload_protocol = esptool
extra_scripts = ota_web_upload.py
upload_protocol = custom
custom_upload_url = http://192.168.20.1/doupdate

lib_deps =
  https://github.com/simonttp78/AsyncTCP @ ^2.0.0
  https://github.com/simonttp78/ESPAsyncWebServer @ ^2.0.0
  makuna/NeoPixelBus @ ^2.8.0
  mikalhart/TinyGPSPlus @ ^1.1.0
  arduino-libraries/LiquidCrystal @ ^1.0.7
  mathertel/LiquidCrystal_PCF8574 @^2.2.0
  bblanchon/ArduinoJson @ ^7.2.0
  https://github.com/thingSoC/embedis @ ^1.2.0
  rweather/Crypto @ ^0.4.0
  JChristensen/Timezone @ ^1.2.4

[env:lolin32]
board = lolin32
board_build.partitions = partitions_custom.csv
build_flags =
  -I src/modules/
  '-D CORE_DEBUG_LEVEL=${common.debug_level}'
